// <auto-generated />
using System;
using Boccialyzer.Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Boccialyzer.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:hstore", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Boccialyzer.Domain.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnName("Caption")
                        .HasAnnotation("Npgsql:Comment", "Опис ролі");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnName("CreatedBy")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи, що створив запис");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("CreatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час внесення");

                    b.Property<bool>("IsAdministrator")
                        .HasColumnName("IsAdministrator")
                        .HasAnnotation("Npgsql:Comment", "Адміністратор?");

                    b.Property<bool>("IsDefault")
                        .HasColumnName("IsDefault")
                        .HasAnnotation("Npgsql:Comment", "За замовчуванням");

                    b.Property<bool>("IsExpert")
                        .HasColumnName("IsExpert")
                        .HasAnnotation("Npgsql:Comment", "Експерт?");

                    b.Property<bool>("IsManager")
                        .HasColumnName("IsManager")
                        .HasAnnotation("Npgsql:Comment", "Менеджер?");

                    b.Property<bool>("IsOwner")
                        .HasColumnName("IsOwner")
                        .HasAnnotation("Npgsql:Comment", "Наш співробітник?");

                    b.Property<bool>("IsSuperUser")
                        .HasColumnName("IsSuperUser")
                        .HasAnnotation("Npgsql:Comment", "Суперюзер?");

                    b.Property<bool>("IsSystem")
                        .HasColumnName("IsSystem")
                        .HasAnnotation("Npgsql:Comment", "Системна?");

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnName("UpdatedBy")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи, що модифікував запис");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnName("UpdatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час редагування");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AppRoles");
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<Guid?>("CountryId")
                        .HasColumnName("CountryId")
                        .HasAnnotation("Npgsql:Comment", "Національність");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnName("CreatedBy")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи, що створив запис");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("CreatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час внесення");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnName("DateOfBirth")
                        .HasAnnotation("Npgsql:Comment", "Дата народження");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .HasColumnName("FirstName")
                        .HasMaxLength(50)
                        .HasAnnotation("Npgsql:Comment", "Ім'я");

                    b.Property<int>("Gender")
                        .HasColumnName("Gender")
                        .HasAnnotation("Npgsql:Comment", "Стать");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("LastName")
                        .HasMaxLength(50)
                        .HasAnnotation("Npgsql:Comment", "Прізвище");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnName("PlayerId")
                        .HasAnnotation("Npgsql:Comment", "Ідентифікатор гравця");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnName("UpdatedBy")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи, що модифікував запис");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnName("UpdatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час редагування");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.HasIndex("UserName");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.Ball", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("Id")
                        .HasAnnotation("Npgsql:Comment", "Ідентифікатор");

                    b.Property<int>("Box")
                        .HasColumnName("Box")
                        .HasAnnotation("Npgsql:Comment", "Ігрова зона");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnName("CreatedBy")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи, що створив запис");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnName("CreatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час внесення");

                    b.Property<int>("DeadBallType")
                        .HasColumnName("DeadBallType")
                        .HasAnnotation("Npgsql:Comment", "Типи м'ячів поза грою");

                    b.Property<int>("Distance")
                        .HasColumnName("Distance")
                        .HasAnnotation("Npgsql:Comment", "Дистанція");

                    b.Property<int>("Index");

                    b.Property<bool>("IsDeadBall")
                        .HasColumnName("IsDeadBall")
                        .HasAnnotation("Npgsql:Comment", "М'яч поза грою?");

                    b.Property<bool>("IsJack");

                    b.Property<bool>("IsPenalty")
                        .HasColumnName("IsPenalty")
                        .HasAnnotation("Npgsql:Comment", "Штрафний м'яч?");

                    b.Property<Guid>("PlayerId")
                        .HasColumnName("PlayerId")
                        .HasAnnotation("Npgsql:Comment", "Гравець");

                    b.Property<int>("Rating")
                        .HasColumnName("Rating")
                        .HasAnnotation("Npgsql:Comment", "Оцінка");

                    b.Property<int>("ShotType")
                        .HasColumnName("ShotType")
                        .HasAnnotation("Npgsql:Comment", "Тип кидка");

                    b.Property<Guid?>("StageId")
                        .HasColumnName("StageId")
                        .HasAnnotation("Npgsql:Comment", "Період гри");

                    b.Property<Guid?>("TrainingId")
                        .HasColumnName("TrainingId")
                        .HasAnnotation("Npgsql:Comment", "Тренування");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnName("UpdatedBy")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи, що модифікував запис");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnName("UpdatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час редагування");

                    b.HasKey("Id");

                    b.HasIndex("Box");

                    b.HasIndex("DeadBallType");

                    b.HasIndex("Distance");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ShotType");

                    b.HasIndex("StageId");

                    b.HasIndex("TrainingId");

                    b.ToTable("Balls");

                    b.HasAnnotation("Npgsql:Comment", "М'ячі");
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<Guid?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("Id")
                        .HasAnnotation("Npgsql:Comment", "Ідентифікатор");

                    b.Property<string>("Alpha2")
                        .HasColumnName("Alpha2")
                        .HasAnnotation("Npgsql:Comment", "Alpha2");

                    b.Property<string>("Alpha3")
                        .HasColumnName("Alpha3")
                        .HasAnnotation("Npgsql:Comment", "Alpha3");

                    b.Property<int>("Code")
                        .HasColumnName("Code")
                        .HasAnnotation("Npgsql:Comment", "Код країни");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnName("CreatedBy")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи, що створив запис");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnName("CreatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час внесення");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasAnnotation("Npgsql:Comment", "Назва");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnName("UpdatedBy")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи, що модифікував запис");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnName("UpdatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час редагування");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("Name");

                    b.ToTable("Countries");

                    b.HasAnnotation("Npgsql:Comment", "Країни");
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.LinkToPlayers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Bib");

                    b.Property<int>("Box");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<int>("Discriminator");

                    b.Property<Guid>("PlayerId");

                    b.Property<Guid?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("LinkToPlayers");

                    b.HasDiscriminator<int>("Discriminator");
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("Id")
                        .HasAnnotation("Npgsql:Comment", "Ідентифікатор");

                    b.Property<Guid>("AppUserId")
                        .HasColumnName("AppUserId")
                        .HasAnnotation("Npgsql:Comment", "Ідентифікатор Користувача системи");

                    b.Property<int>("AvgPointBlue");

                    b.Property<int>("AvgPointRed");

                    b.Property<int>("CompetitionEvent")
                        .HasColumnName("CompetitionEvent")
                        .HasAnnotation("Npgsql:Comment", "Competition Event");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnName("CreatedBy")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи, що створив запис");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnName("CreatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час внесення");

                    b.Property<DateTime>("DateTimeStamp")
                        .HasColumnName("DateTimeStamp")
                        .HasAnnotation("Npgsql:Comment", "Дата та час проведення");

                    b.Property<int>("EliminationStage")
                        .HasColumnName("EliminationStage")
                        .HasAnnotation("Npgsql:Comment", "Етап на вибування");

                    b.Property<string>("FlagBlue")
                        .HasColumnName("FlagBlue")
                        .HasAnnotation("Npgsql:Comment", "Ідентифікатор прапору для синіх");

                    b.Property<string>("FlagRed")
                        .HasColumnName("FlagRed")
                        .HasAnnotation("Npgsql:Comment", "Ідентифікатор прапору для червоних");

                    b.Property<int>("MatchType")
                        .HasColumnName("MatchType")
                        .HasAnnotation("Npgsql:Comment", "Тип матчу");

                    b.Property<int>("PoolStage")
                        .HasColumnName("PoolStage")
                        .HasAnnotation("Npgsql:Comment", "Етап пулу");

                    b.Property<int>("ScoreBlue")
                        .HasColumnName("ScoreBlue")
                        .HasAnnotation("Npgsql:Comment", "Рахунок синіх");

                    b.Property<int>("ScoreRed")
                        .HasColumnName("ScoreRed")
                        .HasAnnotation("Npgsql:Comment", "Рахунок червоних");

                    b.Property<Guid?>("TournamentId")
                        .HasColumnName("TournamentId")
                        .HasAnnotation("Npgsql:Comment", "Турнір");

                    b.Property<Guid?>("TrainingId")
                        .HasColumnName("TrainingId")
                        .HasAnnotation("Npgsql:Comment", "Тренування");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnName("UpdatedBy")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи, що модифікував запис");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnName("UpdatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час редагування");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CompetitionEvent");

                    b.HasIndex("EliminationStage");

                    b.HasIndex("MatchType");

                    b.HasIndex("PoolStage");

                    b.HasIndex("TournamentId");

                    b.HasIndex("TrainingId");

                    b.ToTable("Matches");

                    b.HasAnnotation("Npgsql:Comment", "Матчі");
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("Id")
                        .HasAnnotation("Npgsql:Comment", "Ідентифікатор");

                    b.Property<Guid?>("CountryId")
                        .HasColumnName("CountryId")
                        .HasAnnotation("Npgsql:Comment", "Країна");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnName("CreatedBy")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи, що створив запис");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnName("CreatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час внесення");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnName("FullName")
                        .HasAnnotation("Npgsql:Comment", "Ім'я та прізвище");

                    b.Property<bool>("IsBisFed")
                        .HasColumnName("IsBisFed")
                        .HasAnnotation("Npgsql:Comment", "Чи є гравцем BISFed?");

                    b.Property<int>("PlayerClassification")
                        .HasColumnName("PlayerClassification")
                        .HasAnnotation("Npgsql:Comment", "Класифікація");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnName("UpdatedBy")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи, що модифікував запис");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnName("UpdatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час редагування");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasAnnotation("Npgsql:Comment", "Гравці");
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.Stage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("Id")
                        .HasAnnotation("Npgsql:Comment", "Ідентифікатор");

                    b.Property<int>("AvgPointBlue");

                    b.Property<int>("AvgPointRed");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnName("CreatedBy")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи, що створив запис");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnName("CreatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час внесення");

                    b.Property<int>("Index")
                        .HasColumnName("Index")
                        .HasAnnotation("Npgsql:Comment", "Порядковий номер у грі");

                    b.Property<bool>("IsDisrupted")
                        .HasColumnName("IsDisrupted")
                        .HasAnnotation("Npgsql:Comment", "З порушенням?");

                    b.Property<bool>("IsTieBreak")
                        .HasColumnName("IsTieBreak")
                        .HasAnnotation("Npgsql:Comment", "Тай-брейк?");

                    b.Property<Guid>("MatchId")
                        .HasColumnName("MatchId")
                        .HasAnnotation("Npgsql:Comment", "Ідентифікатор матчу");

                    b.Property<int>("ScoreBlue")
                        .HasColumnName("ScoreBlue")
                        .HasAnnotation("Npgsql:Comment", "Рахунок синіх");

                    b.Property<int>("ScoreRed")
                        .HasColumnName("ScoreRed")
                        .HasAnnotation("Npgsql:Comment", "Рахунок червоних");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnName("UpdatedBy")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи, що модифікував запис");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnName("UpdatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час редагування");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Stages");

                    b.HasAnnotation("Npgsql:Comment", "Періоди гри");
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("Id")
                        .HasAnnotation("Npgsql:Comment", "Ідентифікатор");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnName("CreatedBy")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи, що створив запис");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnName("CreatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час внесення");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnName("DateFrom")
                        .HasColumnType("Date")
                        .HasAnnotation("Npgsql:Comment", "Дата початку");

                    b.Property<DateTime>("DateTo")
                        .HasColumnName("DateTo")
                        .HasColumnType("Date")
                        .HasAnnotation("Npgsql:Comment", "Дата завершення");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasAnnotation("Npgsql:Comment", "Назва");

                    b.Property<Guid>("TournamentTypeId")
                        .HasColumnName("TournamentTypeId")
                        .HasAnnotation("Npgsql:Comment", "Тип турниру");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnName("UpdatedBy")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи, що модифікував запис");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnName("UpdatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час редагування");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("TournamentTypeId");

                    b.ToTable("Tournaments");

                    b.HasAnnotation("Npgsql:Comment", "Турніри");
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.TournamentType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("Id")
                        .HasAnnotation("Npgsql:Comment", "Ідентифікатор");

                    b.Property<string>("Abbr")
                        .IsRequired()
                        .HasColumnName("Abbr")
                        .HasAnnotation("Npgsql:Comment", "Абревіатура");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnName("CreatedBy")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи, що створив запис");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnName("CreatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час внесення");

                    b.Property<string>("Icon")
                        .HasColumnName("Icon")
                        .HasAnnotation("Npgsql:Comment", "Іконка");

                    b.Property<bool>("IsBisFed")
                        .HasColumnName("IsBisFed")
                        .HasAnnotation("Npgsql:Comment", "Чи є офіційним турніром BISFed?");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasAnnotation("Npgsql:Comment", "Назва");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnName("UpdatedBy")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи, що модифікував запис");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnName("UpdatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час редагування");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("TournamentTypes");

                    b.HasAnnotation("Npgsql:Comment", "Тип турніру");
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.Training", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("Id")
                        .HasAnnotation("Npgsql:Comment", "Ідентифікатор");

                    b.Property<Guid>("AppUserId")
                        .HasColumnName("AppUserId")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnName("CreatedBy")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи, що створив запис");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnName("CreatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час внесення");

                    b.Property<DateTime>("DateTimeStamp")
                        .HasColumnName("DateTimeStamp")
                        .HasAnnotation("Npgsql:Comment", "Дата та час тренування");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnName("UpdatedBy")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи, що модифікував запис");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnName("UpdatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час редагування");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Trainings");

                    b.HasAnnotation("Npgsql:Comment", "Тренування");
                });

            modelBuilder.Entity("Boccialyzer.Domain.LogEntities.LogDbEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("Id")
                        .HasAnnotation("Npgsql:Comment", "Ідентифікатор");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("CreatedOn")
                        .HasAnnotation("Npgsql:Comment", "Дата та час створення");

                    b.Property<DateTime>("EventDate")
                        .HasColumnName("EventDate")
                        .HasAnnotation("Npgsql:Comment", "Дата та час сповіщення");

                    b.Property<int>("EventLevel")
                        .HasColumnName("EventLevel")
                        .HasAnnotation("Npgsql:Comment", "Рівень сповіщення");

                    b.Property<int>("EventType")
                        .HasColumnName("EventType")
                        .HasAnnotation("Npgsql:Comment", "Тип сповіщення");

                    b.Property<string>("Exception")
                        .HasColumnName("Exception")
                        .HasAnnotation("Npgsql:Comment", "Помилка");

                    b.Property<string>("IpAddress")
                        .HasColumnName("IpAddress")
                        .HasAnnotation("Npgsql:Comment", "IP-адреса");

                    b.Property<string>("KeyValues")
                        .HasColumnName("KeyValues")
                        .HasAnnotation("Npgsql:Comment", "Ідентифікатор запису");

                    b.Property<string>("Message")
                        .HasColumnName("Message")
                        .HasAnnotation("Npgsql:Comment", "Текст сповіщення");

                    b.Property<string>("NewValues")
                        .HasColumnName("NewValues")
                        .HasAnnotation("Npgsql:Comment", "Нове значення");

                    b.Property<string>("OldValues")
                        .HasColumnName("OldValues")
                        .HasAnnotation("Npgsql:Comment", "Старе значення");

                    b.Property<int>("OperationResult")
                        .HasColumnName("OperationResult")
                        .HasAnnotation("Npgsql:Comment", "Результат виконання операції");

                    b.Property<int>("OperationType")
                        .HasColumnName("OperationType")
                        .HasAnnotation("Npgsql:Comment", "Тип операції");

                    b.Property<string>("TableName")
                        .HasColumnName("TableName")
                        .HasAnnotation("Npgsql:Comment", "Сутність");

                    b.Property<string>("UserName")
                        .HasColumnName("UserName")
                        .HasAnnotation("Npgsql:Comment", "Користувач системи");

                    b.HasKey("Id");

                    b.HasIndex("EventLevel");

                    b.HasIndex("EventType");

                    b.ToTable("LogDbEvent");

                    b.HasAnnotation("Npgsql:Comment", "Сповіщення операцій з БД");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AppRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AppUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<Guid>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AppUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AppUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AppUserTokens");
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.MatchToPlayer", b =>
                {
                    b.HasBaseType("Boccialyzer.Domain.Entities.LinkToPlayers");

                    b.Property<bool>("IsSubstitutePlayer");

                    b.Property<Guid>("MatchId");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.StageToPlayer", b =>
                {
                    b.HasBaseType("Boccialyzer.Domain.Entities.LinkToPlayers");

                    b.Property<Guid>("StageId");

                    b.HasIndex("StageId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("Boccialyzer.Domain.Entities.Country", "Country")
                        .WithMany("AppUsers")
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.Ball", b =>
                {
                    b.HasOne("Boccialyzer.Domain.Entities.Player")
                        .WithMany("Balls")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Boccialyzer.Domain.Entities.Stage")
                        .WithMany("Balls")
                        .HasForeignKey("StageId");

                    b.HasOne("Boccialyzer.Domain.Entities.Training")
                        .WithMany("Balls")
                        .HasForeignKey("TrainingId");
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.Match", b =>
                {
                    b.HasOne("Boccialyzer.Domain.Entities.AppUser", "AppUser")
                        .WithMany("Matches")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Boccialyzer.Domain.Entities.Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId");

                    b.HasOne("Boccialyzer.Domain.Entities.Training")
                        .WithMany("Matches")
                        .HasForeignKey("TrainingId");
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.Stage", b =>
                {
                    b.HasOne("Boccialyzer.Domain.Entities.Match", "Match")
                        .WithMany("Stages")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.Tournament", b =>
                {
                    b.HasOne("Boccialyzer.Domain.Entities.TournamentType")
                        .WithMany("Tournaments")
                        .HasForeignKey("TournamentTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.Training", b =>
                {
                    b.HasOne("Boccialyzer.Domain.Entities.AppUser")
                        .WithMany("Trainings")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Boccialyzer.Domain.Entities.AppRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Boccialyzer.Domain.Entities.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Boccialyzer.Domain.Entities.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Boccialyzer.Domain.Entities.AppRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Boccialyzer.Domain.Entities.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Boccialyzer.Domain.Entities.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.MatchToPlayer", b =>
                {
                    b.HasOne("Boccialyzer.Domain.Entities.Match", "Match")
                        .WithMany("MatchToPlayers")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Boccialyzer.Domain.Entities.Player")
                        .WithMany("MatchToPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Boccialyzer.Domain.Entities.StageToPlayer", b =>
                {
                    b.HasOne("Boccialyzer.Domain.Entities.Stage", "Stage")
                        .WithMany("StageToPlayers")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
